spring:
  application:
    name: citronix
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: hamza
    password: hamza
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  tomcat:
    accesslog:
      enabled: true
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
